# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict
from typing_extensions import Literal

import httpx

from ..._types import Body, Omit, Query, Headers, NotGiven, omit, not_given
from ..._utils import path_template, maybe_transform, async_maybe_transform
from ..._compat import cached_property
from ..._resource import SyncAPIResource, AsyncAPIResource
from ..._response import (
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
)
from ...pagination import SyncSkipLimit, AsyncSkipLimit
from ..._base_client import AsyncPaginator, make_request_options
from ...types.print_mail import (
    tracker_list_params,
    tracker_create_params,
    tracker_update_params,
    tracker_retrieve_visits_params,
)
from ...types.print_mail.tracker_list_response import TrackerListResponse
from ...types.print_mail.tracker_create_response import TrackerCreateResponse
from ...types.print_mail.tracker_delete_response import TrackerDeleteResponse
from ...types.print_mail.tracker_update_response import TrackerUpdateResponse
from ...types.print_mail.tracker_retrieve_response import TrackerRetrieveResponse
from ...types.print_mail.tracker_retrieve_visits_response import TrackerRetrieveVisitsResponse

__all__ = ["TrackersResource", "AsyncTrackersResource"]


class TrackersResource(SyncAPIResource):
    """Create and manage Trackers.

    Trackers can be used to track interactions in your orders through
    personalized URLs and QR codes.

    As a brief introduction to using Trackers in your orders, a QR code can be
    generated by using the Tracker's ID as a merge variable in your orders HTML
    and Templates. The following example HTML uses Trackers to generate
    personalized URLs (PURLs) in your orders.

    See the following guide for more details: https://postgrid.readme.io/reference/trackers-1
    """

    @cached_property
    def with_raw_response(self) -> TrackersResourceWithRawResponse:
        """
        This property can be used as a prefix for any HTTP method call to return
        the raw response object instead of the parsed content.

        For more information, see https://www.github.com/postgrid/postgrid-python#accessing-raw-response-data-eg-headers
        """
        return TrackersResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> TrackersResourceWithStreamingResponse:
        """
        An alternative to `.with_raw_response` that doesn't eagerly read the response body.

        For more information, see https://www.github.com/postgrid/postgrid-python#with_streaming_response
        """
        return TrackersResourceWithStreamingResponse(self)

    def create(
        self,
        *,
        redirect_url_template: str,
        url_expire_after_days: Literal[30, 60, 90, 180, 365],
        description: str | Omit = omit,
        metadata: Dict[str, object] | Omit = omit,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TrackerCreateResponse:
        """
        Create a Tracker.

        Args:
          redirect_url_template: The base template for URLs generated by this Tracker.

          url_expire_after_days: The number of days generated Tracker URLs remain valid.

          description: An optional string describing this resource. Will be visible in the API and the
              dashboard.

          metadata: See the section on Metadata.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        return self._post(
            "/print-mail/v1/trackers",
            body=maybe_transform(
                {
                    "redirect_url_template": redirect_url_template,
                    "url_expire_after_days": url_expire_after_days,
                    "description": description,
                    "metadata": metadata,
                },
                tracker_create_params.TrackerCreateParams,
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=TrackerCreateResponse,
        )

    def retrieve(
        self,
        id: str,
        *,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TrackerRetrieveResponse:
        """
        Retrieve a Tracker by ID.

        Args:
          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return self._get(
            path_template("/print-mail/v1/trackers/{id}", id=id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=TrackerRetrieveResponse,
        )

    def update(
        self,
        id: str,
        *,
        redirect_url_template: str,
        url_expire_after_days: Literal[30, 60, 90, 180, 365],
        description: str | Omit = omit,
        metadata: Dict[str, object] | Omit = omit,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TrackerUpdateResponse:
        """
        Update a Tracker by ID.

        Args:
          redirect_url_template: The base template for URLs generated by this Tracker.

          url_expire_after_days: The number of days generated Tracker URLs remain valid.

          description: An optional string describing this resource. Will be visible in the API and the
              dashboard.

          metadata: See the section on Metadata.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return self._post(
            path_template("/print-mail/v1/trackers/{id}", id=id),
            body=maybe_transform(
                {
                    "redirect_url_template": redirect_url_template,
                    "url_expire_after_days": url_expire_after_days,
                    "description": description,
                    "metadata": metadata,
                },
                tracker_update_params.TrackerUpdateParams,
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=TrackerUpdateResponse,
        )

    def list(
        self,
        *,
        limit: int | Omit = omit,
        search: str | Omit = omit,
        skip: int | Omit = omit,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> SyncSkipLimit[TrackerListResponse]:
        """
        Retrieve a paginated list of Trackers.

        Args:
          search: You can supply any string to help narrow down the list of resources. For
              example, if you pass `"New York"` (quoted), it will return resources that have
              that string present somewhere in their response. Alternatively, you can supply a
              structured search query. See the documentation on `StructuredSearchQuery` for
              more details.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        return self._get_api_list(
            "/print-mail/v1/trackers",
            page=SyncSkipLimit[TrackerListResponse],
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=maybe_transform(
                    {
                        "limit": limit,
                        "search": search,
                        "skip": skip,
                    },
                    tracker_list_params.TrackerListParams,
                ),
            ),
            model=TrackerListResponse,
        )

    def delete(
        self,
        id: str,
        *,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TrackerDeleteResponse:
        """Delete a Tracker by ID.

        Note that this operation cannot be undone.

        Args:
          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return self._delete(
            path_template("/print-mail/v1/trackers/{id}", id=id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=TrackerDeleteResponse,
        )

    def retrieve_visits(
        self,
        id: str,
        *,
        limit: int | Omit = omit,
        search: str | Omit = omit,
        skip: int | Omit = omit,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> SyncSkipLimit[TrackerRetrieveVisitsResponse]:
        """
        Retrieve a paginated list of visits for a Tracker.

        Args:
          search: You can supply any string to help narrow down the list of resources. For
              example, if you pass `"New York"` (quoted), it will return resources that have
              that string present somewhere in their response. Alternatively, you can supply a
              structured search query. See the documentation on `StructuredSearchQuery` for
              more details.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return self._get_api_list(
            path_template("/print-mail/v1/trackers/{id}/visits", id=id),
            page=SyncSkipLimit[TrackerRetrieveVisitsResponse],
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=maybe_transform(
                    {
                        "limit": limit,
                        "search": search,
                        "skip": skip,
                    },
                    tracker_retrieve_visits_params.TrackerRetrieveVisitsParams,
                ),
            ),
            model=TrackerRetrieveVisitsResponse,
        )


class AsyncTrackersResource(AsyncAPIResource):
    """Create and manage Trackers.

    Trackers can be used to track interactions in your orders through
    personalized URLs and QR codes.

    As a brief introduction to using Trackers in your orders, a QR code can be
    generated by using the Tracker's ID as a merge variable in your orders HTML
    and Templates. The following example HTML uses Trackers to generate
    personalized URLs (PURLs) in your orders.

    See the following guide for more details: https://postgrid.readme.io/reference/trackers-1
    """

    @cached_property
    def with_raw_response(self) -> AsyncTrackersResourceWithRawResponse:
        """
        This property can be used as a prefix for any HTTP method call to return
        the raw response object instead of the parsed content.

        For more information, see https://www.github.com/postgrid/postgrid-python#accessing-raw-response-data-eg-headers
        """
        return AsyncTrackersResourceWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncTrackersResourceWithStreamingResponse:
        """
        An alternative to `.with_raw_response` that doesn't eagerly read the response body.

        For more information, see https://www.github.com/postgrid/postgrid-python#with_streaming_response
        """
        return AsyncTrackersResourceWithStreamingResponse(self)

    async def create(
        self,
        *,
        redirect_url_template: str,
        url_expire_after_days: Literal[30, 60, 90, 180, 365],
        description: str | Omit = omit,
        metadata: Dict[str, object] | Omit = omit,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TrackerCreateResponse:
        """
        Create a Tracker.

        Args:
          redirect_url_template: The base template for URLs generated by this Tracker.

          url_expire_after_days: The number of days generated Tracker URLs remain valid.

          description: An optional string describing this resource. Will be visible in the API and the
              dashboard.

          metadata: See the section on Metadata.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        return await self._post(
            "/print-mail/v1/trackers",
            body=await async_maybe_transform(
                {
                    "redirect_url_template": redirect_url_template,
                    "url_expire_after_days": url_expire_after_days,
                    "description": description,
                    "metadata": metadata,
                },
                tracker_create_params.TrackerCreateParams,
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=TrackerCreateResponse,
        )

    async def retrieve(
        self,
        id: str,
        *,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TrackerRetrieveResponse:
        """
        Retrieve a Tracker by ID.

        Args:
          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return await self._get(
            path_template("/print-mail/v1/trackers/{id}", id=id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=TrackerRetrieveResponse,
        )

    async def update(
        self,
        id: str,
        *,
        redirect_url_template: str,
        url_expire_after_days: Literal[30, 60, 90, 180, 365],
        description: str | Omit = omit,
        metadata: Dict[str, object] | Omit = omit,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TrackerUpdateResponse:
        """
        Update a Tracker by ID.

        Args:
          redirect_url_template: The base template for URLs generated by this Tracker.

          url_expire_after_days: The number of days generated Tracker URLs remain valid.

          description: An optional string describing this resource. Will be visible in the API and the
              dashboard.

          metadata: See the section on Metadata.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return await self._post(
            path_template("/print-mail/v1/trackers/{id}", id=id),
            body=await async_maybe_transform(
                {
                    "redirect_url_template": redirect_url_template,
                    "url_expire_after_days": url_expire_after_days,
                    "description": description,
                    "metadata": metadata,
                },
                tracker_update_params.TrackerUpdateParams,
            ),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=TrackerUpdateResponse,
        )

    def list(
        self,
        *,
        limit: int | Omit = omit,
        search: str | Omit = omit,
        skip: int | Omit = omit,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncPaginator[TrackerListResponse, AsyncSkipLimit[TrackerListResponse]]:
        """
        Retrieve a paginated list of Trackers.

        Args:
          search: You can supply any string to help narrow down the list of resources. For
              example, if you pass `"New York"` (quoted), it will return resources that have
              that string present somewhere in their response. Alternatively, you can supply a
              structured search query. See the documentation on `StructuredSearchQuery` for
              more details.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        return self._get_api_list(
            "/print-mail/v1/trackers",
            page=AsyncSkipLimit[TrackerListResponse],
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=maybe_transform(
                    {
                        "limit": limit,
                        "search": search,
                        "skip": skip,
                    },
                    tracker_list_params.TrackerListParams,
                ),
            ),
            model=TrackerListResponse,
        )

    async def delete(
        self,
        id: str,
        *,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> TrackerDeleteResponse:
        """Delete a Tracker by ID.

        Note that this operation cannot be undone.

        Args:
          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return await self._delete(
            path_template("/print-mail/v1/trackers/{id}", id=id),
            options=make_request_options(
                extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
            ),
            cast_to=TrackerDeleteResponse,
        )

    def retrieve_visits(
        self,
        id: str,
        *,
        limit: int | Omit = omit,
        search: str | Omit = omit,
        skip: int | Omit = omit,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AsyncPaginator[TrackerRetrieveVisitsResponse, AsyncSkipLimit[TrackerRetrieveVisitsResponse]]:
        """
        Retrieve a paginated list of visits for a Tracker.

        Args:
          search: You can supply any string to help narrow down the list of resources. For
              example, if you pass `"New York"` (quoted), it will return resources that have
              that string present somewhere in their response. Alternatively, you can supply a
              structured search query. See the documentation on `StructuredSearchQuery` for
              more details.

          extra_headers: Send extra headers

          extra_query: Add additional query parameters to the request

          extra_body: Add additional JSON properties to the request

          timeout: Override the client-level default timeout for this request, in seconds
        """
        if not id:
            raise ValueError(f"Expected a non-empty value for `id` but received {id!r}")
        return self._get_api_list(
            path_template("/print-mail/v1/trackers/{id}/visits", id=id),
            page=AsyncSkipLimit[TrackerRetrieveVisitsResponse],
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
                query=maybe_transform(
                    {
                        "limit": limit,
                        "search": search,
                        "skip": skip,
                    },
                    tracker_retrieve_visits_params.TrackerRetrieveVisitsParams,
                ),
            ),
            model=TrackerRetrieveVisitsResponse,
        )


class TrackersResourceWithRawResponse:
    def __init__(self, trackers: TrackersResource) -> None:
        self._trackers = trackers

        self.create = to_raw_response_wrapper(
            trackers.create,
        )
        self.retrieve = to_raw_response_wrapper(
            trackers.retrieve,
        )
        self.update = to_raw_response_wrapper(
            trackers.update,
        )
        self.list = to_raw_response_wrapper(
            trackers.list,
        )
        self.delete = to_raw_response_wrapper(
            trackers.delete,
        )
        self.retrieve_visits = to_raw_response_wrapper(
            trackers.retrieve_visits,
        )


class AsyncTrackersResourceWithRawResponse:
    def __init__(self, trackers: AsyncTrackersResource) -> None:
        self._trackers = trackers

        self.create = async_to_raw_response_wrapper(
            trackers.create,
        )
        self.retrieve = async_to_raw_response_wrapper(
            trackers.retrieve,
        )
        self.update = async_to_raw_response_wrapper(
            trackers.update,
        )
        self.list = async_to_raw_response_wrapper(
            trackers.list,
        )
        self.delete = async_to_raw_response_wrapper(
            trackers.delete,
        )
        self.retrieve_visits = async_to_raw_response_wrapper(
            trackers.retrieve_visits,
        )


class TrackersResourceWithStreamingResponse:
    def __init__(self, trackers: TrackersResource) -> None:
        self._trackers = trackers

        self.create = to_streamed_response_wrapper(
            trackers.create,
        )
        self.retrieve = to_streamed_response_wrapper(
            trackers.retrieve,
        )
        self.update = to_streamed_response_wrapper(
            trackers.update,
        )
        self.list = to_streamed_response_wrapper(
            trackers.list,
        )
        self.delete = to_streamed_response_wrapper(
            trackers.delete,
        )
        self.retrieve_visits = to_streamed_response_wrapper(
            trackers.retrieve_visits,
        )


class AsyncTrackersResourceWithStreamingResponse:
    def __init__(self, trackers: AsyncTrackersResource) -> None:
        self._trackers = trackers

        self.create = async_to_streamed_response_wrapper(
            trackers.create,
        )
        self.retrieve = async_to_streamed_response_wrapper(
            trackers.retrieve,
        )
        self.update = async_to_streamed_response_wrapper(
            trackers.update,
        )
        self.list = async_to_streamed_response_wrapper(
            trackers.list,
        )
        self.delete = async_to_streamed_response_wrapper(
            trackers.delete,
        )
        self.retrieve_visits = async_to_streamed_response_wrapper(
            trackers.retrieve_visits,
        )
