# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import builtins
from typing import Dict, Optional
from datetime import datetime
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from ..._models import BaseModel

__all__ = ["TrackerUpdateResponse"]


class TrackerUpdateResponse(BaseModel):
    id: str
    """A unique ID prefixed with tracker\\__"""

    created_at: datetime = FieldInfo(alias="createdAt")
    """The UTC time at which this resource was created."""

    live: bool
    """`true` if this is a live mode resource else `false`."""

    object: Literal["tracker"]
    """Always `tracker`."""

    redirect_url_template: str = FieldInfo(alias="redirectURLTemplate")
    """The base template for URLs generated by this Tracker."""

    unique_visit_count: int = FieldInfo(alias="uniqueVisitCount")
    """The unique number of interactions the Tracker has had."""

    updated_at: datetime = FieldInfo(alias="updatedAt")
    """The UTC time at which this resource was last updated."""

    url_expire_after_days: Literal[30, 60, 90, 180, 365] = FieldInfo(alias="urlExpireAfterDays")
    """The number of days generated Tracker URLs remain valid."""

    visit_count: int = FieldInfo(alias="visitCount")
    """The total number of interactions the Tracker has had."""

    description: Optional[str] = None
    """An optional string describing this resource.

    Will be visible in the API and the dashboard.
    """

    metadata: Optional[Dict[str, builtins.object]] = None
    """See the section on Metadata."""
