# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict
from typing_extensions import Literal, Required, Annotated, TypedDict

from ..._utils import PropertyInfo

__all__ = ["TrackerUpdateParams"]


class TrackerUpdateParams(TypedDict, total=False):
    redirect_url_template: Required[Annotated[str, PropertyInfo(alias="redirectURLTemplate")]]
    """The base template for URLs generated by this Tracker."""

    url_expire_after_days: Required[Annotated[Literal[30, 60, 90, 180, 365], PropertyInfo(alias="urlExpireAfterDays")]]
    """The number of days generated Tracker URLs remain valid."""

    description: str
    """An optional string describing this resource.

    Will be visible in the API and the dashboard.
    """

    metadata: Dict[str, object]
    """See the section on Metadata."""
